### ISSUE TITLE
Black video after compression 

### ISSUE THREAD

**Issue by NiklasLehnfeld** [numandev1/react-native-compressor#96] opened 2022-02-16 14:52 UTC
### Current behavior
After compression video has codecs: AAC, H.263. 
Therefore it cannot be played by videoplayer in webapp. 
Format is .mp4

### Expected behavior
Video has codecs: AAC, H.264 and can be played in a videoplayer in webapp.

### Platform

- [X] Android
- [ ] iOS

### React Native Version
v.0.66.4

### React Native Compressor Version
v1.5.1

### Reproducible Steps And Demo
Reproducible with a Lenovo M10 Tab. 

### Notes
Unfortunately we also cannot reproduce that issue. We just got that issue from a user. The video cannot be played by any web application. But can be played by QuickTime or Windows Media Player. After opening the video in QuickTime and exporting it again, the codec changed from AAC, H.263 to AAC, H.264. And then it is working fine within the web applications. For that user its always reproducible. 

We are using the compression simply like:
```
await Video.compress(mediaFile.uri, {
    compressionMethod: 'auto',
});
```

**Comment by nomi9995** [comment] 2022-02-17 05:33
@NiklasLehnfeld I will investigate. but videos are playing for web on my side.

**Comment by timges** [comment] 2022-02-21 11:11
@nomi9995 Any updates on this one? We were able to confirm that it's definetly the compression that changes the video codec.

**Comment by nomi9995** [comment] 2022-02-22 05:33
@timges I am too much. busy in office work, maybe I will investigate and add this in 3 to 4 days.

**Comment by maqboolayaz** [comment] 2022-03-07 08:14
Hi Numan !! 
Do you have any update on this issue? :-)

**Comment by nomi9995** [comment] 2022-03-07 08:37
@maqboolayaz I am too much busy with an office project. hopefully I will try to see it in one or two days.

**Comment by sandeepkallat** [comment] 2022-03-10 11:17
@nomi9995 Unfortunately, we have no source video which converts to H.263, so we are also not able to reproduce it. The issue is in customer's phone because we record live and compress - not upload an existing video. So, what we also know is that the resultant video has Dimension: 144 x 176 and codec AAC, H.263. 

Happens only in some phone models like Huawei P30 Pro, enovo M10, Samsung A40 etc

**Comment by ValentineCodes** [comment] 2022-11-14 07:29
Getting the same issue on my Tecno Pouvoir 4 pro. Black screen after compressing video. Audio not working as well

**Comment by glisom** [comment] 2023-01-19 00:21
I am also seeing this from Android videos

**Comment by numandev1** [comment] 2023-08-24 06:41
@glisom @NiklasLehnfeld can you help me to reproduce this issue, i wanna fix it on this weekend

**Comment by NiklasLehnfeld** [comment] 2023-08-24 07:03
@numandev1 Sorry, 2 years later I  work on a different product and I'm not involved in this anymore.

**Comment by numandev1** [comment] 2023-09-14 22:47
fixed in the latest version, please feel free to reopen it if you get this issue again

**Closed by numandev1** 2023-09-14 22:47 UTC
Labels: Feature, priority issue
