### ISSUE TITLE
iOS Xcode build error after manual installation

### ISSUE THREAD

**Issue by realfelixyu** [numandev1/react-native-compressor#76] opened 2022-01-03 06:49 UTC
### Current behavior
After doing the iOS manual setup(I'm on bare workflow btw, just ejected expo), running in xcode gives following build error:

**error opening input file '/Users/......../node_modules/react-native-compressor/ios/Video/Compressor-Bridging-Header.h' (No such file or directory)**

It looks like the react-native-compressor/ios/Video/ directory doesn't have Compressor-bridging-Header.h
So I copied Compressor-bridging-Header.h from react-native-compressor/ios/ to Video directory. then I get 

**/Users/.........../node_modules/react-native-compressor/ios/Video/Compressor-Bridging-Header.h:4:9: 'React/RCTBridgeModule.h' file not found**

and

**failed to emit precompiled header '/Users/........../Library/Developer/Xcode/DerivedData/.............../PrecompiledHeaders/Compressor-Bridging-Header-swift_2FUMZMGWGJN5S-clang_1UF3F5AFOI7VT.pch' for bridging header '/Users/.................node_modules/react-native-compressor/ios/Video/Compressor-Bridging-Header.h'**

### Expected behavior
Able to run on simulator without having build errors

### Platform
- [X] iOS

### React Native Version
0.63

### React Native Compressor Version
0.5.11

### Reproducible Steps And Demo
Yarn add the library and go through steps 1-4 of iOS manual installation.

**Comment by nomi9995** [comment] 2022-01-03 07:09
@realfelixyu can you add minimal repro through the GitHub repo? because it was working on my side.

**Comment by nomi9995** [comment] 2022-01-28 21:55
I think it is already fixed. feel free to reopen if you see this problem again. thanks.

**Comment by jaexplorer** [comment] 2022-02-03 23:45
No i'm getting this too

**Comment by nomi9995** [comment] 2022-02-06 12:13
@jaexplorer @realfelixyu can you make reproducible example because it is not reproducing on my side.

**Comment by jaexplorer** [comment] 2022-02-06 12:55
I believe it has to do with having XCode 13. Can you confirm?

**Comment by nomi9995** [comment] 2022-02-07 05:51
@jaexplorer I am using `13.2` version of `xcode` but not getting this issue. everything is working good on my side

**Comment by jaexplorer** [comment] 2022-02-07 06:53
@nomi9995 Okay well, I cannot install it manually, or automatically (as per other issues posted aswell). I cannot produce a reproducable scenario for you. But I see others experiencing the same issue. I don't know the cause.

**Comment by jaexplorer** [comment] 2022-02-07 06:54
On version 0.63.2 btw react native

**Comment by nomi9995** [comment] 2022-02-07 07:00
@jaexplorer can you try this error
```
yarn add react-native-compressor@rnlessthan65
```

**Comment by nomi9995** [comment] 2022-02-14 17:49
@jaexplorer any update?

**Comment by DanC5** [comment] 2023-01-23 14:24
@numandev1 I am having the same problem and just opened a fresh issue with all my details, https://github.com/Shobbak/react-native-compressor/issues/144

Thanks

**Comment by numandev1** [comment] 2023-08-19 08:26
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment] 2023-09-14 22:47
fixed in the latest version, please feel free to reopen if you get this issue again

**Closed by numandev1** 2023-09-14 22:47 UTC
