### ISSUE TITLE
getRealPath(uri, "image") bug?

### ISSUE THREAD

**Issue by yudistiraashadi** [numandev1/react-native-compressor#100] opened 2022-03-07 03:42 UTC
### Current behavior

My current code:
```
const res = await DocumentPicker.pickSingle({
    type: [DocumentPicker.types.images],
})

let realPath = await getRealPath(res.uri, "image")

const result = await ImageCompressor.compress(realPath, {
    compressionMethod: "auto",
})
```

`getRealPath(uri, "image")` return the original uri, but with added `file://` in front. When I used the uri returned from `getRealPath()` on 
```
const result = await ImageCompressor.compress(realPath, {
    compressionMethod: "auto",
})
```
An error shows
![image](https://user-images.githubusercontent.com/18660006/156963488-3d9f2318-7cf3-4c6f-8cd2-5d88bfd57d6d.png)

This is the returned value from `DocumentPicker.pickSIngle()`
![image](https://user-images.githubusercontent.com/18660006/156963829-3a43ce3e-c7f9-451e-b159-237a5241a861.png)

This is the returned value from `getRealPath(uri, "image")`
![image](https://user-images.githubusercontent.com/18660006/156963880-e908e7f2-6223-4d18-ab7a-06900bd86d2e.png)

### Expected behavior
`getRealPath(uri, "image")` return an uri I can use for `image.compress()`

### Platform

- [X] Android

### React Native Version
0.67.2

### React Native Compressor Version
1.5.2

### Reproducible Steps And Demo
- Pick an image using `react-native-document-picker` in Android, it will return an uri with `content://`
- Input the uri on `getRealPath(uri, "image")`
- Input the real path returned from `getRealPath(uri, "image")` on `image.compress()`

**Comment by nomi9995** [comment] 2022-03-07 05:20
@yudistiraAshadi can you tell me your android device and OS modal and can you add a reproducible GitHub example here?

**Comment by yudistiraAshadi** [comment] 2022-03-07 07:15
> @yudistiraAshadi can you tell me your android device and OS modal and can you add a reproducible GitHub example here?

This is in Android Emulator from Android Studio
![image](https://user-images.githubusercontent.com/18660006/156985156-c15652ce-38c5-4fe4-94a1-6641406dd366.png)

**Comment by yudistiraAshadi** [comment] 2022-03-07 07:17
> @yudistiraAshadi can you tell me your android device and OS modal and can you add a reproducible GitHub example here?

I included the steps and a copy of my code on top. I hope that's enough.

**Comment by thareekanvar** [comment] 2022-06-19 09:08
@yudistiraAshadi 

This is the reasoni think.. u should give permission.

```
const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
      {
        title: 'Storage Permission',
        message: 'App needs access to memory to upload the file ',
      },
    );
    if (granted != PermissionsAndroid.RESULTS.GRANTED) {
      Toast.show({
        type: 'error',
        text1: 'Permission Issue.',
        text2: 'You need to give storage permission to upload the file.',
      });

      return false;
    }
```

**Comment by Raghavmunjal** [comment] 2022-08-18 07:06
I have the same error, any updates ?

**Comment by numandev1** [comment] 2023-08-19 08:26
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment] 2023-09-15 07:00
Does this issue still exist?

**Comment by numandev1** [comment] 2023-10-02 22:41
fixed in the latest version, please feel free to reopen this issue again if this issue happens again

**Closed by numandev1** 2023-10-02 22:41 UTC
