### ISSUE TITLE
Not working on iOS with mov files

### ISSUE THREAD

**Issue by Bayramito** [numandev1/react-native-compressor#101] opened 2022-03-18 15:43 UTC
### Current behavior

Its not working on IOS with .mov file format at all.

### Platform

- [X] iOS

### React Native Version

react-native: "0.64.2"

### React Native Compressor Version
react-native-compressor: "0.5.17"

**Comment by pierroo** [comment] 2022-04-15 15:41
@Bayramito did you find any solution to this? 
it is quite sad indeed :/

**Comment by stefanleoussis** [comment] 2022-05-05 18:53
@Bayramito Yes indeed

**Comment by Bayramito** [comment] 2022-05-05 18:59
> @Bayramito Yes indeed
I used a converter in a promisr and used mp4.

but it might work on the newest version i think.

**Comment by talha-mts** [comment] 2023-04-13 07:15
Any update it's still not working.
& also application crashes whenever we try to compress mov file.

**Comment by numandev1** [comment] 2023-08-19 08:26
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by vincentzierigen** [comment] 2023-10-05 19:45
We need an urgent fix for this, the app crashes every single time

**Comment by numandev1** [comment] 2023-10-05 20:42
@vincentzierigen it is working on my side with mov file, can you send me your mov file so i can reproduce this issue on my side and fix it

**Comment by numandev1** [comment] 2023-10-05 21:14
@vincentzierigen did you check latest version?

**Comment by vincentzierigen** [comment] 2023-10-06 00:03
> @vincentzierigen did you check latest version?

I just did and now it works! Thank you so much!

**Closed** 2023-10-06 00:45 UTC
Labels: priority issue
