### ISSUE TITLE
orientation data gets removed after compression

### ISSUE THREAD

**Issue by jeemercado** [numandev1/react-native-compressor#146] opened 2023-02-21 07:10 UTC
### Current behavior
- orientation data gets removed after compression, resulting in rotation of images on some cases, specifically Android.
- test in a Samsung Phone when using camera taken images. my guess is photos taken by samsung camera all default to horizontal/landscape orientation and gets rotated 90 CW for portraits

### Platform

- [X] Android
- [X] iOS

### React Native Version 
0.66.7

### React Native Compressor Version
1.5.2

**Comment by jeemercado** [comment] 2023-02-21 07:12
For reference, here are the images I used:
![compressed](https://user-images.githubusercontent.com/53922337/220273267-5e469fd6-5b94-45d0-b9a8-366511a7d887.jpg)
![not compressed](https://user-images.githubusercontent.com/53922337/220273310-3667db75-ce9c-4dd2-932f-b786ba61c974.jpg)

**Comment by neuxregime** [comment] 2023-06-22 18:34
+1

**Comment by briangonzalez** [comment] 2023-07-24 16:53
Any movement on this one @numandev1?

**Comment by numandev1** [comment] 2023-07-24 17:23
@briangonzalez can you provide me any reproducible example because it is working well on my side

**Comment by numandev1** [comment] 2023-07-24 17:26
@jeemercado No, I don't have a Samsung device, without reproduce I am unable to fix it

**Comment by numandev1** [comment] 2023-07-24 17:33
@jeemercado After 3 to 4 weeks, I am going to revamp the compressor package, hopefully, I will fix this issue by revamping

**Comment by numandev1** [comment] 2023-08-19 08:22
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment] 2023-09-14 22:41
can you check `1.8.2` version if you got this issue again?

**Comment by numandev1** [comment] 2023-10-02 22:41
fixed in the latest version, please feel free to reopen this issue again if this issue happens again

**Closed by numandev1** 2023-10-02 22:41 UTC

**Comment by Smigi33** [comment] 2024-01-11 18:19
@numandev1  Same issue when taking picture via react-native-vision-camera and compression is setting to manual (on auto it's normal). Image picker working good.

Testing on iPhone 7 iOS 15.8 and couple of android devices.

React-native 0.71.8
"react-native-image-picker": "^5.6.0",
"react-native-compressor": "^1.8.23",
"react-native-vision-camera": "^2.15.4",
